### ISSUE TITLE
How to get CASIA-E dataset?

### ISSUE THREAD

**Issue by nerddd** [wj1tr0y/gait_extractor#2]
Hello, can you tell me how to download casia-e dataset? I didn't find the download link? Thank you

**Comment by wj1tr0y** [comment]
sry, been a little bit busy lately. CASIA-E is not open to public right now. 
(等paper出来吧

**Comment by ZhengLeon** [comment]
Is CASIA-E open to public now?

**Comment by developfeng** [comment]
CASIA-E is now shared from : https://cstr.cn/31253.11.sciencedb.07226
